"""add User

Revision ID: 4dfc0a8afeb4
Revises: 9c290c0ec370
Create Date: 2026-08-06 16:08:41.298883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfc0a8afeb4'
down_revision: Union[str, Sequence[str], None] = '9c290c0ec370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'])
    op.add_column('phones', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('phones', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('phones', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'phones', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phones', type_='foreignkey')
    op.drop_column('phones', 'user_id')
    op.drop_column('phones', 'updated_at')
    op.drop_column('phones', 'created_at')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'user_id')
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    op.drop_table('users')
    # ### end Alembic commands ###
